services:
  minecraft:
    image: ghcr.io/edwardtakev/mcvanilla:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - /mnt/media/docker/minecraft:/app
    environment:
      # The URL where the server JAR will be downloaded from
      MC_JAR_URL: "https://fill-data.papermc.io/v1/objects/8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e/paper-1.21.8-60.jar"
      # The name the jar file will be saved as upon downloading 
      MC_JAR: "server.jar"
      # Memory allocation: -Xms2G → minimum heap = 2GB | -Xmx4G → maximum heap = 4GB
      JAVA_OPTS: "-Xms2G -Xmx4G"
