services:
  minecraft:
    image: ghcr.io/edwardtakev/mcvanilla:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data:/app
    environment:
      MC_JAR_URL: "https://fill-data.papermc.io/v1/objects/8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e/paper-1.21.8-60.jar"
      MC_JAR: "server.jar"
      JAVA_OPTS: "-Xms2G -Xmx4G"
      MC_ARGS: "nogui"
