services:
  minecraft:
    build: .
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data:/app
    environment:
      # Provide the JAR download link
      MC_JAR_URL: "https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/132/downloads/paper-1.21.1-132.jar"
      MC_JAR: "server.jar"
      JAVA_OPTS: "-Xms1G -Xmx4G"
      MC_ARGS: "nogui"
    command: >
      sh -c "
        if [ ! -f /app/$MC_JAR ]; then
          echo 'Downloading server jar...';
          wget -O /app/$MC_JAR $MC_JAR_URL;
        fi &&
        java $JAVA_OPTS -jar /app/$MC_JAR $MC_ARGS
      "
