services:
  minecraft:
    image: ghcr.io/edwardtakev/mc-docker:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - /mnt/media/docker/minecraft:/app
    environment:
      # Server type: default (Vanilla/Paper) or curseforge
      SERVER_TYPE: "default"

      # URL to download server: JAR for Vanilla/Paper, zip for CurseForge
      MC_SERVER_URL: "https://papermc.io/api/v2/projects/paper/versions/1.21.8/builds/60/downloads/paper-1.21.8-60.jar"

      # Main server file inside /app: JAR for Vanilla/Paper, can be ignored for CurseForge
      MC_SERVER_MAIN: "server.jar"

      # Java memory allocation
      JAVA_OPTS: "-Xms2G -Xmx4G"
